CREATE CONSTRAINT user_id IF NOT EXISTS FOR (u:USER) REQUIRE u.user_id IS UNIQUE;
CREATE CONSTRAINT station_id IF NOT EXISTS FOR (s:STATION) REQUIRE s.station_id IS UNIQUE;
CREATE CONSTRAINT trip_id IF NOT EXISTS FOR (t:TRIP) REQUIRE t.trip_id IS UNIQUE;

